### ISSUE TITLE
Case statements in notificationReceived not found

### ISSUE THREAD

**Issue by gisteren** [Jopyth/MMM-Remote-Control#131]
Hello Jopyth,

I was working on getting access through the api to a module I am working on and my notifications were not recognized. Looking into your code I think I found the issue.

In api.js you have the following code:
let re = /notification \=\=\=? (?:"|')([A-Z_-]+?)(?:"|')|case (?:"|')([A-Z_-]+)(?:"|')/g;
let m;
let availabeActions = [];
if (re.test(content)) {
    content.match(re).forEach((match) => {:
         let n = match.replace(re, '$1');

In the first let you actually generate a regex that will provide you with 2 groups: $1 and $2. The matched if statements will always be found in the $1 and the case statements will always be found in $2, so you need to process both to get all the notifications of a module.

I tested it by replacing the $1 with $2 which caused all the modules using if statements to not show up and the ones with a case statement were showing up.

Regards,

Richard

**Comment by ezeholz** [comment]
Hey! So I think I didn't fully understand your issue. If you can explain a little more about it, I'll be glad to help you and fix the problem. However, I'm gonna close this issue because it's more than a year old, but feel free to reopen it and give me more details about this bug.
Keep Programming ;D
