### ISSUE TITLE
Support for custom replies

### ISSUE THREAD

**Issue by nixmeer** [Jopyth/MMM-Remote-Control#145]
Hello,

I have a switch in my HomeKit to turn on and off my mirror using homebridge. However, there are two things that would improve this module for me:

1.) homebridge just calls the MMM-Remote-Control-URLs. I need the mirror to reply with 0 or 1 to confirm if it did the right thing. Right now it returns a json object that homebridge won't understand

2.) Another URL would be helpful to get the current display status. 

Maybe a separate mqtt client could take over this part. This would allow the current code to be untouched and shift this module towards an universal integration into an existing smart home.

In an older version of this module, I just copied the lines for the MONITORON and OFF command, called them HOMEBRIDGE-MONITORON and it would work. But somehow, this part changed and my javascript skills are not good enough to figure it out.

Thanks in advance!

**Comment by ezeholz** [comment]
Hey! So, it's not possible to get the first into action, because it's most useful giving an JSON most than just a 0 or 1. You can use a middleware just to change the response to one that you need. The second one I'm gonna look but I think that it's actually implemented. I'm gonna close this issue, but feel free to create another one if you feel like it. Cheers and keep programming ;D
