### ISSUE TITLE
This device is not allowed to access your mirror.  Please check your config.js or config.js.sample to change this.

### ISSUE THREAD

**Issue by larserno** [Jopyth/MMM-Remote-Control#16]
When I try to open the url in my webbrowser, I get this message:
This device is not allowed to access your mirror. 
Please check your config.js or config.js.sample to change this.
What can I do?

**Comment by israel05** [comment]
This has been notified like one thousand times or so. It is because the new version bans certain ip ranges.
in config/config.js file add the following row

  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1","::ffff:192.168.0.1/16", "::1"],

between "port" and "language". These "192.168.0.1/16" are because my lan has that ip range, if yours is 192.168.1.1 or anything like that, then change it properly

**Comment by larserno** [comment]
ok thank you kind sir

**Comment by Jopyth** [comment]
Thanks @israel05 for clearing that up. Will update my mirror to the new development version this weekend, and hopefully be able to adapt this module and the readme to it.
