### ISSUE TITLE
SSL_ERR when connecting to MM2

### ISSUE THREAD

**Issue by jdelandtsheer** [Jopyth/MMM-Remote-Control#163]
hey, I've been trying for several days now to get this module to work but it's getting on my nerves. 

this is my conf: 

`address: "0.0.0.0", 
	port: 8080,
	ipWhitelist:[],
`
`module: 'MMM-Remote-Control',
  position: 'bottom_left',
    		config: {
        		apiKey: ""         // Optional, See API/README.md for details
    			}
		},`

At first when I tried to connect via my android phone, i got "Connection refused" and now I got "SSL_ERR"
Also my pi's IP isn't showing too but i don't really care much about that.

**Comment by ezeholz** [comment]
Hey! I'm gonna close this issue now, because it's been almost a year. However, the answer is that you made a few mistakes into the config itself. Your config file is missing the modules array. I'll let you the docs from [MM](https://docs.magicmirror.builders/modules/configuration.html#example).
Cheers :D
