### ISSUE TITLE
Monitor On not working

### ISSUE THREAD

**Issue by ezeholz** [Jopyth/MMM-Remote-Control#168]
Hey there! So, I was researching about this, now I have MagicMirror running on an Ubuntu computer, I managed to change both monitor on and off to work with my computer. But, there is a small little problem, and It's that the monitor doesn't even turn on when I use the command.
```javascript
customCommand: {
    monitorOnCommand: 'xset dpms force on',
    monitorOffCommand: 'xset dpms force off',
    monitorStatusCommand: 'if xset -q|grep -q "Off: 0"; then echo true; else echo false; fi'
}
```
Am I doing something wrong?

**Comment by BerndKohl** [comment]
I had the same problem and did a little digging.
For me the problem was the monitorStatusCommand: It did return an "invalid" string if the monitor was off.
It has to return "false" if the monitor is turned off and "true" it is is turned on.
Please check by running the command
`if xset -q|grep -q "Off: 0"; then echo true; else echo false; fi`
on your mirror once when the monitor is turned off and once when it is turned on.
What do you get?

**Comment by ezeholz** [comment]
So I found that is a problem of the `xset q` command, basically it gives always Off: 0.
Something that can work is using the `Monitor is` on the line below. That also have a bug because if you wake up the computer without the script, it will stay as Off. In the worst scenario, you'll have to press a second time the button. 
The way of doing it may be
```javascript
monitorStatusCommand: 'if xset -q|grep -q "Monitor is Off"; then echo true; else echo false; fi'
```

**Comment by ezeholz** [comment]
Managed to work, this is the code that works perfectly in a replacement of the PI version:
```javascript
customCommand: {
    monitorOnCommand: 'xset dpms force on',
    monitorOffCommand: 'xset dpms force off',
    monitorStatusCommand: 'if xset -q|grep -q "Monitor is Off"; then echo false; else echo true; fi'
}
```
All that pasted in the config of this module turns on and off the monitor perfectly, also working for toggle and status.
