### ISSUE TITLE
Change Monitor On/Off to Linux command

### ISSUE THREAD

**Issue by chen32g** [Jopyth/MMM-Remote-Control#178]
Hi,
There is a way to change the Monitor On/Off command to run linux command:
vcgencmd display_power 0 for turn off
vcgencmd display_power 1 for turn on

Thank you.

**Comment by ezeholz** [comment]
Of course there is, it's over [here](https://github.com/Jopyth/MMM-Remote-Control#using-custom-commands).

I encourage you to close this issue if you feel that your problem is solve, otherwise ask again and I'm gonna reply as fast as I can. ;)

**Comment by chen32g** [comment]
Hi,

I try it.
The monitorOffCommand is working but the monitorOnCommand not working.
Please advise.

Thank you.

**Comment by ezeholz** [comment]
Do you use the monitorStatusCommand? Because the monitorOnCommand works in a strange way, using the status of the monitor. If you have a command for the program to see if your monitor is on or off, please try it and let me know. Otherwise, I can look into the code, and show you what you can change to "hard code" the on and off of the monitor.

**Comment by bjorndegroot** [comment]
Hi,

Same here. The monitorOffCommand is working but the monitorOnCommand not working. I'm not using the monitorStatusCommand. So that cannot be the issue I think.

**Comment by ezeholz** [comment]
Hey,
Actually that's the issue, because the program checks if the screen is on or off, and acts accordingly, as it's stands on the [monitosStatusCommand declaration](https://github.com/Jopyth/MMM-Remote-Control/blob/2daec303f5ddea8288daedfa2941dc9e9bba4d8b/node_helper.js#L605)

Try to use a monitorStatus instead, and the monitorOn command will work as expected.
If you don't know where to start, I'll let you the line I use in config:
`monitorStatusCommand: 'if xset -q|grep -q "Monitor is Off"; then echo false; else echo true; fi'`

**Comment by bjorndegroot** [comment]
I configured it like this, but turn on the screen still doesn't work to turn the screen on.

{
			module: "MMM-Remote-Control",
			config: {
			customCommand: {
        		monitorOnCommand: 'vcgencmd display_power 1',
        		monitorOffCommand: 'vcgencmd display_power 0',
        		monitorStatusCommand: 'if xset -q|grep -q "Monitor is Off"; then echo false; else echo true; fi'
    }
				
			}
		},

**Comment by ezeholz** [comment]
Just to be sure, I checked which command you can use with the Status. And it's better for you to use this line instead: 
`monitorStatusCommand: 'if vcgencmd -1; then echo true; else echo false; fi'`

I have to do the whole xset command because I don't have vcgencmd. But if you have that command, that should work.

**Comment by BLoodConstructions** [comment]
After tryin all solutions. This one worked for me:
`customCommand: {
                                                monitorOnCommand: 'vcgencmd display_power 1',
                                                monitorOffCommand: 'vcgencmd display_power 0',
                                                monitorStatusCommand: 'if vcgencmd display_power | grep 1 >/dev/null 2>&1; then echo true; else echo false; fi'
                                                },`
http://192.1xx.1xx.xx:8080/remote?action=MONITORTOGGLE
http://192.1xx.1xx.xx:8080/remote?action=MONITORTON
http://192.1xx.1xx.xx:8080/remote?action=MONITOROFF

**Comment by bjorndegroot** [comment]
Thanks for sharing!

**Comment by BLoodConstructions** [comment]
Does it work for you too?

**Comment by bjorndegroot** [comment]
Yeah, this works fine for me too. Thanks for that. Just for others who wanna use it too... This is my config for MMM-Remote-Control right now.


{
			module: "MMM-Remote-Control",
			config: {
			customCommand: { monitorOnCommand: 'vcgencmd display_power 1', monitorOffCommand: 'vcgencmd display_power 0', monitorStatusCommand: 'if vcgencmd display_power | grep 1 >/dev/null 2>&1; then echo true; else echo false; fi' },
				
			}
		},

**Comment by hipitihop** [comment]
For those that have more then one monitor, multiple HDMI like Raspberry Pi4, then it's better to be specific about the device. You can see list of device ids via `tvservice -l`

So here is my config, using device 2, which is the first hdmi port:

```js
{ customCommand:
   {
	monitorOnCommand: "vcgencmd display_power 1 2",
	monitorOffCommand: "vcgencmd display_power 0 2",
	monitorStatusCommand: "if vcgencmd display_power -1 | grep -q \"display_power=1\"; then echo true; else echo false; fi"
   }
}
```

See other [vcgencmd docs here](https://www.raspberrypi.org/documentation/raspbian/applications/vcgencmd.md)

**Comment by chen32g** [comment]
Great, thank you all.
This command solve the problem
customCommand: { monitorOnCommand: 'vcgencmd display_power 1', monitorOffCommand: 'vcgencmd display_power 0', monitorStatusCommand: 'if vcgencmd display_power | grep 1 >/dev/null 2>&1; then echo true; else echo false; fi' },

**Comment by Einixx** [comment]
I ran into the same issue. 
Thanks for this solution
