### ISSUE TITLE
Use MMM motion detector and PS3 cam

### ISSUE THREAD

**Issue by airart** [Jopyth/MMM-Remote-Control#189]
can I use your module to switch from a screensaver with clock (full screen) to the magic mirror (all te modules) when I pass in front of the camera? then go from one module to another with motion detect? no face recognize
thank you very much

**Comment by ezeholz** [comment]
Hey, 
So this module isn't able to do that kind of things. This one can communicate every other module to show or hide things, or wake up your screen, but you'll need another one to detect movement, maybe other for module carrousel, and one for the PS3 eye.
Beware that the PS3 eye doesn't have fully functionality because of drivers, and it's possible that you don't find a proper module to use that cam.
