### ISSUE TITLE
Remove Black Translucent Background 

### ISSUE THREAD

**Issue by henrydotsg** [Jopyth/MMM-Remote-Control#208]
How do I remove the black translucent background?
Currently it’s orating if I have a photo background. 

![179C0F8B-AC0B-4390-8F47-A222B21E9685](https://user-images.githubusercontent.com/69137267/89292080-4f28de80-d68e-11ea-8db0-2515652bdc47.jpeg)

**Comment by ezeholz** [comment]
Hey! So, this repository is no longer maintained. So I'm taking care and trying to help everyone who's having issues.

Did you try changing some css files? Tell me if you still in the need of help, and we'll work out into a completely working solution for you.

Cheers :D

**Comment by henrydotsg** [comment]
I have change the settings in the main.css and it’s working already.  I’m not sure how to change it i custom css.

**Comment by ezeholz** [comment]
So it's working now? Cool, that's what we're looking for.
I encourage you to put over here what files did you change and what change did you do, in order to help other people that could be struggle with the same issue. 
I also recommend for you to close the issue if u think it's resolved, and maybe create a PR updating those files. 
Good luck and keep creating. :D

**Comment by henrydotsg** [comment]
I commented out the overlay to archive the result. 

//        var bgColor = "rgba(0,0,0," + (100 - brightness) / 100 + ")";
//        overlay.style.backgroundColor = bgColor;
