### ISSUE TITLE
This device is not allowed to access your mirror. Please check your config.js or config.js.sample to change this. AND Monitor on and off buttons not working

### ISSUE THREAD

**Issue by anthpham** [Jopyth/MMM-Remote-Control#211]
I made sure
address: "0.0.0.0", and added my computer and phone's ip addresses to the ipWhitelist, and I fixed the comma error in the 
{
   module: "MMM-Remote-Control",
   position: "bottom_left",
   config{}
},
part too. Still getting the error "This device is not allowed to access your mirror. Please check your config.js or config.js.sample to change this." when I go to http://192.168.x.x:8080/remote.html

**Comment by AnthonyVPham** [comment]
I ended up just allowing all ip address by leaving the white list blank like so:
ipWhitelist: [],
This isn't secure but it connects.
Now I have the problem that none of the buttons in the remote interface work. I mainly just want to be able to turn the monitor on and off. I've done the solution for this here: [https://github.com/Jopyth/MMM-Remote-Control/issues/178#issuecomment-619364624]
Did not work.

**Comment by ezeholz** [comment]
If the ipwhitelist is blank and you can access, but allowing some of them don't work, maybe you're not configuring them correctly. I have `ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.0.x/y", "192.168.0.x/x"]`
Are you using it the same way?

**Comment by ezeholz** [comment]
About the remote interface, not a single button work? It's possible that just monitor on and off don't work, because they depends on your OS, and how it's configure to work. I have a fork where I fix some issues about monitor, and also shutdown and reboot. Take a look, and ask me again if you're still having an error :D

**Comment by AnthonyVPham** [comment]
What is the x/y and the x/x that you put at the end of those ip addresses? This is what I have, with fake numbers ofc
`ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1","::ffff:192.168.0.51", "::ffff:192.168.1.942"],`
And yes, I've tried pretty much every button and none of them work.
I have now also tried using your fork. I've don both an empty white list and the white list above, to the same result. I can only access the interface if my white list is empty and even then none of the buttons work. I do like how it looks tho. Much nicer than original.

**Comment by ezeholz** [comment]
Okay, I think that I know what's happening. Let's say that your external IP from where you want to connect with the mirror is 192.168.0.51, right? So in the whitelist you have to add 192.168.0.51. The you add ::ffff, and that's when you're using IPV6. If you didn't know what that is, you probably don't have it. So go ahead and add 192.168.0.51 into the whitelist, without the ::ffff part.

**Comment by ezeholz** [comment]
Pressing the buttons and not having any response, give you an error code? Did you try refreshing the browser after the mirror starts?

**Comment by AnthonyVPham** [comment]
Thanks! Leaving out the ::ffff: part worked! The buttons still aren't working though. Here's an error I found:
[2020-08-19 15:47:12.458] [LOG]    monitorToggle requested
[2020-08-19 15:47:12.487] [ERROR]  (node:5542) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Also, thank you so much @ezeholz for helping me out! Still sort of new to this thing and I definitely did not expect to get same day replies. I really appreciate it

**Comment by ezeholz** [comment]
Haha, don't worry. I'm here to help. :)
Which version of node are you using? You can see that entering into a terminal and typing `nodejs -v`
Also, please tell me your npm version (`npm -v`) and your OS. :D

**Comment by AnthonyVPham** [comment]
Node v10.21.0 and npm v6.14.4. OS is Raspbian GNU/Linx 10.
I also just noticed that going into Power->Shutdown menu gives me the image attached. Power->Restart shows similarly, with undefined buttons. 
<img width="447" alt="shutdown menu" src="https://user-images.githubusercontent.com/60859926/90689503-cdac8100-e235-11ea-8528-f0a32db0db92.PNG">

**Comment by ezeholz** [comment]
Sounds to me that's maybe some problem with the installation itself. Did you use the `npm install` command inside the Remote Control folder? Also I'm searching for that error specifically. Can you try using the refresh browser option, and see if it's the same error?

**Comment by AnthonyVPham** [comment]
Yes I did use npm install. I just deleted the repo and recloned it, made sure it was yours, and npm install in the Remote Control folder. I refreshed the browser and the buttons still don't work. Is there a way to output into a txt file more detailed logs? Using npm start and then exiting, I get this:
> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
`[2020-08-19 16:54:41.872] [LOG]    Starting MagicMirror: v2.11.0
[2020-08-19 16:54:41.885] [LOG]    Loading config ...
[2020-08-19 16:54:41.894] [LOG]    Loading module helpers ...
[2020-08-19 16:54:41.899] [LOG]    No helper found for module: clock.
[2020-08-19 16:54:43.228] [LOG]    Initializing new module helper ...
[2020-08-19 16:54:43.230] [LOG]    Module helper loaded: calendar
[2020-08-19 16:54:43.232] [LOG]    No helper found for module: currentweather.
[2020-08-19 16:54:43.234] [LOG]    No helper found for module: weatherforecast.
[2020-08-19 16:54:44.649] [LOG]    Initializing new module helper ...
[2020-08-19 16:54:44.651] [LOG]    Module helper loaded: MMM-NowPlayingOnSpotify
[2020-08-19 16:54:45.133] [LOG]    Initializing new module helper ...
[2020-08-19 16:54:45.135] [LOG]    Module helper loaded: MMM-Remote-Control
[2020-08-19 16:54:45.870] [LOG]    Initializing new module helper ...
[2020-08-19 16:54:45.871] [LOG]    Module helper loaded: MMM-AlexaControl
[2020-08-19 16:54:45.872] [LOG]    No helper found for module: MMM-DailyBuddhismWisdom.
[2020-08-19 16:54:45.873] [LOG]    All module helpers loaded.
[2020-08-19 16:54:46.177] [LOG]    Starting server on port 8080 ... 
[2020-08-19 16:54:46.214] [LOG]    Server started ...
[2020-08-19 16:54:46.217] [LOG]    Connecting socket for: calendar
[2020-08-19 16:54:46.220] [LOG]    Starting node helper for: calendar
[2020-08-19 16:54:46.222] [LOG]    Connecting socket for: MMM-NowPlayingOnSpotify
[2020-08-19 16:54:46.224] [LOG]    Connecting socket for: MMM-Remote-Control
[2020-08-19 16:54:46.226] [LOG]    Starting node helper for: MMM-Remote-Control
[2020-08-19 16:54:46.255] [LOG]    Connecting socket for: MMM-AlexaControl
[2020-08-19 16:54:46.259] [LOG]    MMM-AlexaControl helper, started...
[2020-08-19 16:54:46.261] [LOG]    Sockets connected & modules started ...
[2020-08-19 16:54:46.574] [LOG]    Launching application.
[2020-08-19 16:54:52.422] [LOG]    monitorToggle requested
[2020-08-19 16:54:52.443] [ERROR]  (node:1119) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2020-08-19 16:54:52.445] [ERROR]  (node:1119) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2020-08-19 16:54:52.453] [LOG]    Adding multicast membership for 127.0.0.1
[2020-08-19 16:54:52.456] [LOG]    Adding multicast membership for 192.168.1.198
[2020-08-19 16:54:52.459] [LOG]    server is listening on 11000
[2020-08-19 16:54:52.460] [LOG]    server is listening on 11001
[2020-08-19 16:54:52.461] [LOG]    server is listening on 11002
[2020-08-19 16:54:52.462] [LOG]    server is listening on 11005
[2020-08-19 16:54:52.761] [LOG]    Refreshed access token because it has expired. Expired at: 16:54:52 now is: 16:54:52
[2020-08-19 16:54:52.844] [LOG]    Refreshed access token because it has expired. Expired at: 17:54:52 now is: 16:54:52
[2020-08-19 16:56:35.171] [LOG]    Shutting down server...
[2020-08-19 16:56:35.180] [LOG]    Stopping module helper: calendar
[2020-08-19 16:56:35.182] [LOG]    Stopping module helper: MMM-NowPlayingOnSpotify
[2020-08-19 16:56:35.184] [LOG]    Stopping module helper: MMM-AlexaControl`

**Comment by ezeholz** [comment]
Try disabling any other module apart from the Remote Control. You can do this by entering your config file and adding `disabled: true,` into every module, or commenting those lines.

PD: I found that you're requesting the monitorToggle from [AlexaControl](https://github.com/JoChef2/MMM-AlexaControl/blob/a936501d8eed06c96ba19e87f20499a0dc47ce7c/node_helper.js#L232), and that's why you're not getting any answer into turning it off. Try those codes into a terminal, and see which one it's working for you. You gonna need to change them according to your system.

PD 2: Also, I didn't found anything related to the DEP0005 line into Remote Control code, probably some other module it's throwing that exception. Are you still seeing undefined menus? Do you have the `language: "en",` line in your config?

PD 3: Okay, so the error you're getting is from [NowPlayingOnSpotify](https://github.com/raywo/MMM-NowPlayingOnSpotify/search?q=buffer&unscoped_q=buffer)

How to continue?: Turn off every other module and try again Remote Control. If it's working, you should create an issue on those repositories, showing those errors.

**Comment by AnthonyVPham** [comment]
Strange. I've commented out all other modules beside Remote Control. The interface buttons still don't work and show undefined, even after refreshing the browser. Yes I do have language: "en".
Doing `vcgencmd display_power 0` and `vcgencmd display_power 1` in the terminal both work.
Here is what I have in the config under modules
`{
			module: "MMM-Remote-Control",
			position: "bottom_left",
      		  	// you can hide this module afterwards from the remote control itself
			config: {/*
				customCommand: {monitorOnCommand: 'vcgencmd display_power 1',
						monitorOffCommand: 'vcgencmd display_power 0',
						monitorStatusCommand: 'if vcgencmd display_power | grep 1 >/dev/null 2>&1; then echo true; else echo false; fi'
				}*/
			}
},`

I have tried it both with the custom command and without the custom command. I found this custom command from [https://github.com/Jopyth/MMM-Remote-Control/issues/178#issuecomment-625754221](https://github.com/Jopyth/MMM-Remote-Control/issues/178#issuecomment-625754221). Not sure if it still works actually.
Thanks for your patience!

**Comment by ezeholz** [comment]
Are you using any adblocker to enter the remote menu? Sounds to me that the undefined buttons problem, and also why those don't work it's because some app blocking javascript to work, which is needed in order to send the commands and change the text into the popup. You could try using any other browser to get into the menu. 

If using vcgencmd works for you, and you wanna turn it off using Alexa, you need to search how they use that command, and use it. The #178 solution should work, because the code didn't change at all. But we won't know it until javascript on remote.html works.

**Comment by AnthonyVPham** [comment]
I am using an adblocker. I disabled it, didn't work. I also tried using a different browser. That didn't work either.
Looks like the Alexa module I'm using [https://github.com/JoChef2/MMM-AlexaControl](https://github.com/JoChef2/MMM-AlexaControl) uses it like this:
`if(this.config.vcgencmd =='vcgencmd'){
                device.handler = function(action) {     
                    if(action === 1){
                        exec("vcgencmd display_power 1", opts, (error, stdout, stderr) => {
                            _this.checkForExecError(error, stdout, stderr); 
                        });
                    }if(action === 0){
                        exec("vcgencmd display_power 0", opts, (error, stdout, stderr) => {
                            _this.checkForExecError(error, stdout, stderr); 
                        });
                    }
                }
            }`

**Comment by ezeholz** [comment]
That's weird. In the browser console appear any error? I'll dig into it for a few days, to see which one could be the error. 

With Alexa module, you should put `vcgencmd` into the config `vcgencmd`. Do you try it? Maybe it's a solution.

If you want to, maybe could be good to redownload the Remote Control repository, add a package-lock.json file with the next one 
```json
{
  "name": "Magic-Mirror-Module-Remote-Control",
  "version": "2.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "body-parser": {
      "version": "1.19.0",
      "resolved": "https://registry.npmjs.org/body-parser/-/body-parser-1.19.0.tgz",
      "integrity": "sha1-lrJwnlfJxOCab9Zqj9l5hE9p8Io=",
      "requires": {
        "bytes": "3.1.0",
        "content-type": "~1.0.4",
        "debug": "2.6.9",
        "depd": "~1.1.2",
        "http-errors": "1.7.2",
        "iconv-lite": "0.4.24",
        "on-finished": "~2.3.0",
        "qs": "6.7.0",
        "raw-body": "2.4.0",
        "type-is": "~1.6.17"
      }
    },
    "bytes": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/bytes/-/bytes-3.1.0.tgz",
      "integrity": "sha1-9s95M6Ng4FiPqf3oVlHNx/gF0fY="
    },
    "content-type": {
      "version": "1.0.4",
      "resolved": "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz",
      "integrity": "sha1-4TjMdeBAxyexlm/l5fjJruJW/js="
    },
    "debug": {
      "version": "2.6.9",
      "resolved": "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz",
      "integrity": "sha1-XRKFFd8TT/Mn6QpMk/Tgd6U2NB8=",
      "requires": {
        "ms": "2.0.0"
      }
    },
    "depd": {
      "version": "1.1.2",
      "resolved": "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz",
      "integrity": "sha1-m81S4UwJd2PnSbJ0xDRu0uVgtak="
    },
    "ee-first": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz",
      "integrity": "sha1-WQxhFWsK4vTwJVcyoViyZrxWsh0="
    },
    "http-errors": {
      "version": "1.7.2",
      "resolved": "https://registry.npmjs.org/http-errors/-/http-errors-1.7.2.tgz",
      "integrity": "sha1-T1ApzxMjnzEDblsuVSkrz7zIXI8=",
      "requires": {
        "depd": "~1.1.2",
        "inherits": "2.0.3",
        "setprototypeof": "1.1.1",
        "statuses": ">= 1.5.0 < 2",
        "toidentifier": "1.0.0"
      }
    },
    "iconv-lite": {
      "version": "0.4.24",
      "resolved": "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz",
      "integrity": "sha1-ICK0sl+93CHS9SSXSkdKr+czkIs=",
      "requires": {
        "safer-buffer": ">= 2.1.2 < 3"
      }
    },
    "inherits": {
      "version": "2.0.3",
      "resolved": "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz",
      "integrity": "sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4="
    },
    "media-typer": {
      "version": "0.3.0",
      "resolved": "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz",
      "integrity": "sha1-hxDXrwqmJvj/+hzgAWhUUmMlV0g="
    },
    "mime-db": {
      "version": "1.43.0",
      "resolved": "https://registry.npmjs.org/mime-db/-/mime-db-1.43.0.tgz",
      "integrity": "sha1-ChLgUCZQ5HPXNVNQUOfI9OtPrlg="
    },
    "mime-types": {
      "version": "2.1.26",
      "resolved": "https://registry.npmjs.org/mime-types/-/mime-types-2.1.26.tgz",
      "integrity": "sha1-nJIfwJt+FJpl39wNpNIJlyALCgY=",
      "requires": {
        "mime-db": "1.43.0"
      }
    },
    "ms": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz",
      "integrity": "sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g="
    },
    "on-finished": {
      "version": "2.3.0",
      "resolved": "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz",
      "integrity": "sha1-IPEzZIGwg811M3mSoWlxqi2QaUc=",
      "requires": {
        "ee-first": "1.1.1"
      }
    },
    "qs": {
      "version": "6.7.0",
      "resolved": "https://registry.npmjs.org/qs/-/qs-6.7.0.tgz",
      "integrity": "sha1-QdwaAV49WB8WIXdr4xr7KHapsbw="
    },
    "raw-body": {
      "version": "2.4.0",
      "resolved": "https://registry.npmjs.org/raw-body/-/raw-body-2.4.0.tgz",
      "integrity": "sha1-oc5vucm8NWylLoklarWQWeE9AzI=",
      "requires": {
        "bytes": "3.1.0",
        "http-errors": "1.7.2",
        "iconv-lite": "0.4.24",
        "unpipe": "1.0.0"
      }
    },
    "safer-buffer": {
      "version": "2.1.2",
      "resolved": "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz",
      "integrity": "sha1-RPoWGwGHuVSd2Eu5GAL5vYOFzWo="
    },
    "setprototypeof": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.1.tgz",
      "integrity": "sha1-fpWsskqpL1iF4KvvW6ExMw1K5oM="
    },
    "simple-git": {
      "version": "1.129.0",
      "resolved": "https://registry.npmjs.org/simple-git/-/simple-git-1.129.0.tgz",
      "integrity": "sha1-7d0mEdK/Qcd+HQjNcMC38694UEA=",
      "requires": {
        "debug": "^4.0.1"
      },
      "dependencies": {
        "debug": {
          "version": "4.1.1",
          "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz",
          "integrity": "sha1-O3ImAlUQnGtYnO4FDx1RYTlmR5E=",
          "requires": {
            "ms": "^2.1.1"
          }
        },
        "ms": {
          "version": "2.1.2",
          "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz",
          "integrity": "sha1-0J0fNXtEP0kzgqjrPM0YOHKuYAk="
        }
      }
    },
    "statuses": {
      "version": "1.5.0",
      "resolved": "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz",
      "integrity": "sha1-Fhx9rBd2Wf2YEfQ3cfqZOBR4Yow="
    },
    "toidentifier": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.0.tgz",
      "integrity": "sha1-fhvjRw8ed5SLxD2Uo8j013UrpVM="
    },
    "type-is": {
      "version": "1.6.18",
      "resolved": "https://registry.npmjs.org/type-is/-/type-is-1.6.18.tgz",
      "integrity": "sha1-TlUs0F3wlGfcvE73Od6J8s83wTE=",
      "requires": {
        "media-typer": "0.3.0",
        "mime-types": "~2.1.24"
      }
    },
    "unpipe": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz",
      "integrity": "sha1-sr9O6FFKrmFltIF4KdIbLvSZBOw="
    },
    "uuid": {
      "version": "3.3.3",
      "resolved": "https://registry.npmjs.org/uuid/-/uuid-3.3.3.tgz",
      "integrity": "sha1-RWjwIW54dg7h2/Ok0s9T4iQRKGY="
    }
  }
}
```
and do `npm ci`, mostly to see if any package could be broken.

**Comment by AnthonyVPham** [comment]
Where would I look for for errors?
Yes, I do have vcgencmd set into the config vcgencmd already.
How and where would I add that package?

**Comment by ezeholz** [comment]
When you download the MMM-Remote-Control folder, and add it into the modules folder, then go into the MMM-Remote-Control one, and before running anything you should paste the file I sent you. After that, do `npm ci`. That should install a clean version that should be the same that I'm currently using. Hope it works. El 19 ago. 2020 23:21, Anthony Pham <notifications@github.com> escribió:
Where would I look for for errors?
Yes, I do have vcgencmd set into the config vcgencmd already.
How and where would I add that package?

**Comment by anthpham** [comment]
I reinstalled MM and went to xxx.xxx.x.xxx:8080/index.html but it was unsuccessful. I still got errors:

GET http://xxx.xxx.x.xxx:8080/index.html 404 (Not Found)
DevTools failed to load SourceMap: Could not load content for chrome-extension://blcdfhbibkkjpfdddnmnmhfgjlicebba/js/content_script.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
index.html:1 Refused to load the image 'http://xxx.xxx.x.xxx:8080/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

To get the ip address of the pi you just use hostname -I correct?

**Comment by ezeholz** [comment]
Nice! I was worried for a bit. Hahaha
I hope everything works fine. Reach out again if you need to. 

Keep Programming :D
