### ISSUE TITLE
Monitor On/Off Alternatives

### ISSUE THREAD

**Issue by XoniBlue** [Jopyth/MMM-Remote-Control#225]
Like many before me, Great module. Thank you for the continued support and upkeep. 

I am banging my head at this point; let me explain. I do not like the vgenc or tvservice aspect of MM, instead I do have cec-utils installed to the pi and can successfully through terminal or cron and even changing the node-helper.js (only monitor-off) can turn the Tv on or off. 

` 
                this.thisConfig.customCommand.monitorOnCommand : 
				"sudo echo 'on 0' | cec-client -s -d 1"
              
                this.thisConfig.customCommand.monitorOffCommand :
				"sudo echo 'standby 0' | cec-client -s -d 1"
               
                this.thisConfig.customCommand.monitorStatusCommand :
				"echo 'pow 0' | cec-client -s -d 1"
               
                screenStatus = exec(monitorStatusCommand, opts, (error, stdout, stderr) => {
					if (stdout.indexOf("standby") !== -1 || stdout.indexOf("false") !== -1) {
             
					} else if (stdout.indexOf("on") !== -1 || stdout.indexOf("true") !== -1) {
  

There is the edited node-helper.js snippet, the problem I am facing is that even using custom commands;
`monitorOnCommand: "sudo echo 'on 0' | cec-client -s -d 1",'

		        monitorOffCommand: "sudo echo 'standby 0' | cec-client -s -d 1",

		        monitorStatusCommand: "sudo echo 'pow 0' | cec-client -s -d 1"`

The monitorOn fuction simply does not work. monitorOff works regardless the custom command or not. Once the command has been triggered, I either turn the tv on manually (jk) or use terminal to turn it back on. 

I prefer cec over simply disabling the hdmi so the tv sees no "source" but instead triggering the immediate on/off of the tv itself. 

Any ideas on how I can get the on command to work, side note I believe the status text which can be invoked with 'pow' from the same cec command is correct. Either way the off command worked and on didn't before I changed anything to do with the status. 

Thanks for you time

-Xoni

**Comment by ezeholz** [comment]
Hey! I need to look at the changes I made the past days about monitor. Maybe it's some bug related to that. Let me check further.

**Comment by XoniBlue** [comment]
Let me know what you come up with, I can verify that the monitorOff command is working via remote-control, but not monitorOn. this is of course using the cec controls

**Comment by ezeholz** [comment]
Okay, I think I found the problem, and it's that I actually didn't make a change into the repository, but instead I made those changes locally. I'm gonna try to work this out, and give you a preview as soon as I can.
Also, I encourage you not to change node_helper itself, but to add the commands inside config.js, because every update you'll have to edit the file again, and actually adding them into the config file will work as expected when this thing it's fixed.
Thanks for letting me know this bug ;D

**Comment by ezeholz** [comment]
Check that branch, using
```js
customCommand: {
        monitorOnCommand: "sudo echo 'on 0' | cec-client -s -d 1",
        monitorOffCommand: "sudo echo 'standby 0' | cec-client -s -d 1",
        monitorStatusCommand: "sudo echo 'pow 0' | cec-client -s -d 1",
    }
```
And let me know if it works. :D

**Comment by XoniBlue** [comment]
that branch gave me solid black screen with curser.

**Comment by ezeholz** [comment]
Oops, understood. Let me check what I did wrong. Any log?

**Comment by ezeholz** [comment]
Now it's fine. I'm sorry about the black screen. I tested this one and it's working just fine.
Try not only the menu, but also the api, using `http://YOURIP:8080/api/monitor/on`.

**Comment by XoniBlue** [comment]
I'll check when I get home. I know the api commands via browser were working differently than expected. Meaning you couldn't call on /api

**Comment by XoniBlue** [comment]
confirmed working, Im wondering if you could point me at a cheat sheet to use the api id sure appreciate that. Also im wondering if you have seen this thread [https://forum.magicmirror.builders/topic/9941/mmm-remote-control-cannot-get-api?page=1](url)

**Comment by XoniBlue** [comment]
http://pi-ip:8080/remote?action=MONITORON  - working
http://pi-ip:8080/remote?action=MONITOROFF  - working
http://pi-ip:8080/remote?action=MONITORSTATUS  - not working
http://pi-ip:8080/remote?action=MONITORTOGGLE  - working to shut tv off, not back on. 

also again I added code to the node-helper. I know you suggested against it. but for the wording to look for for on/off status is necessary I think. 

`sudo echo 'pow 0' | cec-client -s -d 1
opening a connection to the CEC adapter...
power status: on`

`sudo echo 'pow 0' | cec-client -s -d 1
opening a connection to the CEC adapter...
power status: standby`

if that helps.

**Comment by ezeholz** [comment]
The api works just fine. You just have to take our the api config from inside the config file, because the Remote Control think that there's an API key installed, when it isn't.

I'm glad that worked out just fine. The toggle one I suspect that doesn't work because you'll probably have to add the standby word inside those arrays I added. You could try that way.

And I'm not against not adding code inside node_helper. It's better for you to have less trouble when we update the Remote Control. Hahah
Also you can fork it, and add it in your own fork, and rebase it every time there's an update. That way you'll be updated, and you wouldn't lost the changes you have made. :D
