### ISSUE TITLE
Strq funktioniert nicht was tun

### ISSUE THREAD

**Issue by Tomaate** [Jopyth/MMM-Remote-Control#226]
Hallo, seit ein paar Tagen steht bei meinem Magic mirror mmm remote control Modul aktualisieren doch wenn ich es aktualisieren will mit Steuerung Q kommt nur ein Blackscreen und ich kann nichts mehr eingeben außerdem sind wir SSH auch nicht ich habe Magic mirror auf einem Raspberry Pi 3 installiert.  Und davor hat alles einwandfrei funktioniert
 Danke.

**Comment by Tomaate** [comment]
Also ich will es mit Steuerung q verlassen und dann ins Terminal gehen aber das funktioniert nicht

**Comment by ezeholz** [comment]
Check if you're getting the last update from the master branch, could be that you're getting the develop one, and that's bringing up an error. Please try to check logs, and can you send your config.js without your personal information?

Also, If you know English, please try to use it. Because I have to use Google Translate, and It's probably not the most accurate program to use when we want to solve an issue.
Cheers :D

**Comment by Tomaate** [comment]
Wie kann ich die config.js öffnen?
(bin ein anfäger sorry wegen der doof fragen)

**Comment by ezeholz** [comment]
Check the main folder of your MagicMirror installation, over there go to config, and open the config.js file with notepad or gedit. Which version of MagicMirror are you using?

**Comment by Tomaate** [comment]
Ich verwende die neuste version von magic mirror 2

**Comment by Tomaate** [comment]
Ich kann das confic.js nicht öffnen da ich ja nicht aus magic mirror mit strq raus komme

**Comment by ezeholz** [comment]
Try using the flag key. Alternatively you can use alt + tab if you run the code manually.

**Comment by ezeholz** [comment]
I'm gonna close this issue now because I didn't receive any answer from you in a week. If you still having this issue, feel free to reopen. Cheers :D
