### ISSUE TITLE
Reverse secureEndpoints

### ISSUE THREAD

**Issue by BKeyport** [Jopyth/MMM-Remote-Control#230]
## Feature Request

secureEndpoints is backwards. If the endpoints are secure, you should be able to indicate it's true. Otherwise, it's false. 

### Description

Clarity. 

### Changelog

Unknown. 

### Requirements

Switch the command's bool around, Alternatively create new tag for the logic to not break existing installs. (behindSecurity?)

**Comment by ezeholz** [comment]
Hey! By default, the secureEndpoints it's true, meaning that the endpoints are secure. In the readme it's `true` just because a lot of people it's gonna use it by default. Inside the wiki it's more explained about it, you believe that we should remove the option from the readme configuration? The idea it's that, despite grabbing the default value, you're able to change it later.

**Comment by BKeyport** [comment]
What I'm saying is that it seems to be backwards. "SecureEndpoints: true" would indicate that it is secure (Behind a firewall, etc). 
You have it as "secureEndpoints: true" indicates that it is not secure.. 

In my mind, "secure" is referring to overall network security, and "endpoints" are referring to what can access it. Am I wrong in this thinking?

**Comment by ezeholz** [comment]
I think that maybe it's my fault about how I write that explanation.
You're getting it right. `secureEndpoints: true` should give the idea that the endpoints are not reachable because their are secure. And that's how it's programmed in the background.
Adding in your config file `secureEndpoints: false` will open those endpoints, allowing anyone to enter. That'll mean that they're not secure anymore. It's that what you meant?

The example in the readme it's more like a placeholder, if you take that line out, doesn't really change anything, because by default those endpoints are secure, and that variable it's set to `true`.

I understand you correctly?

**Comment by BKeyport** [comment]
Think I get it. You're thinking security from the mirror level, where I'm reading it as security from the network level. 

Just a misunderstanding. No worries.

**Comment by ezeholz** [comment]
Well, I tried to explain the better I could. I think that, talking about modules and the mirror itself, it's probably better for all of us to stand in the mirror side.

I'll add this option with more details on the wiki soon. Thanks for letting me know your point!
Cheers :D
