### ISSUE TITLE
Mute and unmute

### ISSUE THREAD

**Issue by jamie0911** [Jopyth/MMM-Remote-Control#254]
Hi sorry to be a pain again is there a way to umute and mute through the remote controll?

**Comment by ezeholz** [comment]
It depends on your OS. For example, in Linux you can do it [this way](https://askubuntu.com/questions/26068/how-do-you-mute-from-the-command-line). For Windows it's a little bit more complicated, because by default there's no way you can mute it from command line, but you can use [this](https://www.nirsoft.net/articles/mute_speaker_command_line.html) software that works pretty good.
