### ISSUE TITLE
Can't hide MMM-CalendarExt2

### ISSUE THREAD

**Issue by MacG-DD** [Jopyth/MMM-Remote-Control#264]
This is my first project with a Raspberry Pi, which I have started this week.

I can’t hide the module MMM-CalendarExt2 with Remote-Control. It is also not offered to me at “Edit View”. With “Hide all” all modules disappear, except the CalendarExt2. With Remote-Control on the cell phone, however, CalendarExt2 can be found under “Updates”. Why not in “Edit View”?

At another Issue, I found the following "command URL":  http://localhost/remote?action=HIDE&force=true&module=$name

I adapted it, and it works with hiding and show.
http://localhost/remote?action=HIDE&force=true&module=MMM-CalendarExt2
http://localhost/remote?action=SHOW&force=true&module=MMM-CalendarExt2

Is there any way I can add this command to Remote-Control?

**Comment by ezeholz** [comment]
Hey! You cannot see the module in module views because, in my short understanding, that module doesn't use position in `config.js`.

What you can do, is use a custom menu to show or hide the module. You can read more about it in [here](https://github.com/Jopyth/MMM-Remote-Control/wiki/Custom-Menus)
Or, to just get over it with some simple coding, set a [class](https://github.com/Jopyth/MMM-Remote-Control/wiki/Classes) for that module.

**Comment by MacG-DD** [comment]
Thank you for your quick reply. The calendar module has a position, but not before the config part.

I will use the class. Are there all modules added, it will work as I would like.

Thanks for your Remote-Control, it gives ones many possibilities.

**Comment by ezeholz** [comment]
Glad to be helpful! I'll close this issue now, but feel free to keep asking in you need help.
Cheers! :D
