### ISSUE TITLE
No working solution for Monitor On/Off – RaspberryPi 4 issue

### ISSUE THREAD

**Issue by JDiaz11** [Jopyth/MMM-Remote-Control#284]
### OS

Debian version: 11 (bullseye)

### NodeJS Version

16.18.1

### MagicMirror Version

2.21.0

### Remote Control Version

2.3.7

### Did you try using just Remote Control alone with MM?

- [X] I have and the error still happening

### Description

Hello-- In your August 28 reply to a user on this matter, you said "        Thank you for reporting this issue! However, this is not a bug, and it's ever inside our [FAQ](https://github.com/Jopyth/MMM-Remote-Control/wiki/FAQ#my-magicmirror-screen-isnt-turning-off). Please refer to it for more information."

But I looked thru the FAQ and it's not in there at all. The only reference to monitor-off not working suggests that a misconfigured custom command is likely the cause. 

The issue is the vcgencmd display_power command itself not working with the Pi 4. I tried using "DISPLAY=:0.0 xrandr --output HDMI-1 --off" as an alternate, but it resets my display rotation to landscape when it turns back on. 

This has been a thing for 3 or 4 years now. 

### Expected behavior

What is the recommended command set please?     

### Current behavior

No response to command

### Possible solution

An alternative command option

### Steps to reproduce

Explained

### Log

```shell
No log- the command returns a response stating the current display on/off state as though being queried vs commanded
```

### config.js

```javascript
Not relevant to issue
```

**Comment by ezeholz** [comment]
Hello! As you stated, and rightfully looked for, this issue is purely about configuration. RC uses those commands to turn on and off the monitor. So if you use them in a console, and they are not working, they will not work either in RC.

Here's another pair of commands that could be helpful, you should test all the options and search what suits best for your environment.
```
xset -display :0 dpms force on
xset -display :0 dpms force off
```

[I'll also link an issue that seems relevant.](https://github.com/raspberrypi/firmware/issues/1224) Again, every environment it's different and uses different commands, please check it out on google BEFORE asking around here. Thanks!

**Comment by JDiaz11** [comment]
Yeah I googled all night -- that's how I learned that the command doesn't work for the Pi 4. Thanks I'll give these a shot.

**Comment by biejay** [comment]
For me this works for turning on in Portrait Mode:

DISPLAY=:0.0 xrandr --output HDMI-1 --auto --rotate right
