### ISSUE TITLE
"No module loaded" after cloning a module

### ISSUE THREAD

**Issue by sko22** [Jopyth/MMM-Remote-Control#50]
Hello, I have cloned the module MMM-bitcoin and renamed MMM-Etheurum for show me the value of etheurums in the mirror. This module works fine but when I am in Edit view of MMM-Remote-Control
(http://localhost:8888/remote.html#edit-menu) iI have this message "No module loaded".
Can you help me?

**Comment by ThibaultAmbert** [comment]
Hello,
Thanks for your work. I have noticed the same bug with 2 others modules : 
https://github.com/jgauth/MMM-GoogleTasks : This one works fine on the mirror.
https://github.com/spectroman/mmm-food2fork-recipes : This one I don't succeed to display it

If I add one of those modules the mirror run but impossible to load module in the remote control or sometime the modules appears (except the module added) but the control have no effect. The save config of your module (1 hide module at start and the brightness to the maximum) don't be applied. 

If I remove the module the config save works and tjjjjjjjjhe command also.

I have added other modules after this and no trouble.

Hope it's help to solve the problem. 

Thanks again for your answer.

**Comment by ezeholz** [comment]
I don't see any problem like this. Tried installing mmm-food2fork-recipes and everything work as expected. You shouldn't clone the same module, tho. There are some files and the module register that you have to change in order to make both work. 

About the bitcoin one, I didn't find the one you're talking. Maybe this issue it's already resolved, but I can't reproduce it. Give me more details If you're still having issues. Cheers :D
