### ISSUE TITLE
Config Update Restarts the MagicMirror

### ISSUE THREAD

**Issue by s-shiva1995** [Jopyth/MMM-Remote-Control#63]
MagicMirror Version: 2.1.3
OS: Linux
H/W: Raspberry Pi 3

Whenever I update config using post method. The mirror needs to restart for loading new config. Is there no way to update magic mirror configuration without restarting it to view the result of updated configuration and when the user is satisfied the config.js file is updated and then mirror restarts(better doesn't restarts) to load the config.js file.

**Comment by s-shiva1995** [comment]
I will be glad to work on this if someone points me in correct direction. I am not able to find the correct solution for this problem.

**Comment by Jopyth** [comment]
This is something with `pm2`. If you used the default installer, I think it configures it in a way, that restarts MagicMirror on file changes. But it should be possible to change the [corresponding script](https://github.com/MichMich/MagicMirror/blob/master/installers/pm2_MagicMirror.json). Needs tinkering with `pm2` though.

**Comment by s-shiva1995** [comment]
I tried using [electron-reload](https://github.com/yan-foto/electron-reload). This now doesn't restarts the mirror but reloads the window due to which there is still a flicker of 1-2sec. How should I add the functionality to update and restart the module which was edited and rest of the screen doesn't reload.

**Comment by ndom91** [comment]
Yeah so pm2 by default watches the config.js file, if theres any changes, it restarts the magicmirror node app. 

Reload seems like it would work as well - check the pm2 configs or possibly even the systemd file for magicmirro (/etc/systemd/system/magicmirror.service [or something .service - def in this folder though])

**Comment by ezeholz** [comment]
Looking into how MagicMirror works, it's necessary to close and reopen the electron, because it's not something we can actually change. In order to change the way it opens, maybe it's better to use the server mode of MagicMirror, but it isn't something we should change without asking the user first.
The other option it's to "emulate" those changes, but that's something we'll need to develop with time. So for now this issue will remain in hold. If anyone have time to develop some sort of solution, feel free to fork and PR, and I'll be glad to merge. :D

**Comment by ezeholz** [comment]
I believe this it's actually implemented right now in the develop branch. I made a new button that ask for restart or reload, if it's just to see how it looks like that way, you should reload the browser and see the changes. I recommend doing a MM Restart when everything it's okay, just to be sure that nothing could be broken in every module itself. :D
