### ISSUE TITLE
Shutdown and Reboot request doesn't close MM

### ISSUE THREAD

**Issue by AgP42** [Jopyth/MMM-Remote-Control#85]
On both request Reboot and Shutdown, the exec command are directly send to the RPI that immediatly apply them without closing on a clean way the MagicMirror before. 

Would it be possible to request "pm2 stop" or "npm stop" before Shutdown or Reboot ?
(and let some time to the RPI to close the MM)

Thanks,

**Comment by ezeholz** [comment]
Hey! I'm soon to implement the custom commands for Shutdown and Reboot. Meaning that you could easily apply what you're talking in this issue. However, this issue is more than two years old, so I'm gonna close it for now. Feel free to open a new one if you feel that the issue wasn't resolve at all. Cheers ;D
