### ISSUE TITLE
Hide module doesn't work?

### ISSUE THREAD

**Issue by IwanZh** [Jopyth/MMM-Remote-Control#88]
I am using Gassispi to trigger hide module but it doesn't work. I tried to hide other module namely MMM-RTSPStream but it also failed to hide the module. Are there any changes in Magic Mirror 2.4.1 that causes this bug? 
It was using this following GET request to trigger show/hide module
http://192.168.1.5:8080/remote?action=SHOW&module=module_2_currentweather
http://192.168.1.5:8080/remote?action=HIDE&module=module_2_currentweather

And also MMM-ModuleScheduler does turn off monitor on a specified schedule, but failed to turn on monitor 

Thanks in advance

**Comment by Madseason41** [comment]
Same here. I cant hide modules via the same technique above.

**Comment by razio80** [comment]
same here..

**Comment by johnzaccari04** [comment]
same here

**Comment by ezeholz** [comment]
Hey you all! First of all, I believe there is a change into the API function, for the better we all can get onboard into the API. The docs about it say that you should use `/api/module/:module/:action`, in the form of:
```
http://192.168.1.5:8080/api/module/module_2_currentweather/hide
http://192.168.1.5:8080/api/module/module_2_currentweather/show
```
That'll actually show or hide the module. I'll let you the [example](https://documenter.getpostman.com/view/6167403/Rzfni66c#66e395bc-7438-482b-a377-27048ffeb1c2) I use.

**Comment by ezeholz** [comment]
About the screen turning off but not on, I'll markdown that it's probably some code necessary into this, because every screen turn on and off in different ways, you should search any that satisfies it. For example, I believe that tvservice can turn off the screen putting the system in a non-wake state. So, you should use any other code to turn on and off the screen. Soon I'll fix some code between that function, so stay tune about new updates. Cheers to all ;D
