### ISSUE TITLE
Modifying remote control screen

### ISSUE THREAD

**Issue by arekcygan** [Jopyth/MMM-Remote-Control#94]
Hi All,

I have a quick question:

I would like to add to remote control few additional buttons using which I will control https://github.com/MunichStef/MMM_Webradio module. 
Above module accepts notifications but the question is which files and how should be modified in remote control module in order to achieve it?

**Comment by Maxmark11** [comment]
Hello arekcygan, firstly I wanted to thank you for your attempt to create this function. I was thinking to make this happen and after all I found this topic. So I added everything and it worked! Only the Previous station didnt work, because  remote control need notification "WEBRADIO_PREV" not "WEBRADIO_PREVIOUS"... after all, I wanted to get rid off these new tabs, so I added some lines to code for closing these new tabs. It will only flash and come back to Radio settings :) 

`"radio-onoff": function() {`
`	popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_ONOFF", "_blank");`
`popup.close();`
`},`
`"radio-up": function() {`
`popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_VOLUP", "_blank");`
`popup.close();`
`},`
`"radio-down": function() {`
`popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_VOLDOWN", "_blank");`
`popup.close();`
`},`
`"radio-next": function() {`
`popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_NEXT", "_blank");`
`popup.close();`
`},`
`"radio-previous": function() {`
`popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_PREV", "_blank");`
`popup.close();`
`},`

**Comment by RafaelCota** [comment]
Something strange is happening with my remote. I edited _remote.html_ and _remote.js_ as you, but:

1. If I try it from my laptop (Chrome browser) everything works fine
2. If I try it from **my cell phone** (Chrome or Safari) the menu items appear, **but do nothing**.  Tried from several phone with same result. Only works from a laptop.

Any ideas?

> Hello arekcygan, firstly I wanted to thank you for your attempt to create this function. I was thinking to make this happen and after all I found this topic. So I added everything and it worked! Only the Previous station didnt work, because remote control need notification "WEBRADIO_PREV" not "WEBRADIO_PREVIOUS"... after all, I wanted to get rid off these new tabs, so I added some lines to code for closing these new tabs. It will only flash and come back to Radio settings :)
> 
> `"radio-onoff": function() {`
> `	popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_ONOFF", "_blank");`
> `setTimeout(function(){popup.close();},5);`
> `},`
> `"radio-up": function() {`
> `popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_VOLUP", "_blank");`
> `setTimeout(function(){popup.close();},5);`
> `},`
> `"radio-down": function() {`
> `popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_VOLDOWN", "_blank");`
> `setTimeout(function(){popup.close();},5);`
> `},`
> `"radio-next": function() {`
> `popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_NEXT", "_blank");`
> `setTimeout(function(){popup.close();},5);`
> `},`
> `"radio-previous": function() {`
> `popup = window.open("/remote?action=NOTIFICATION&notification=WEBRADIO_PREV", "_blank");`
> `setTimeout(function(){popup.close();},5);`
> `},`

**Comment by Maxmark11** [comment]
Try to change the value of timeout to 100 - 500 (0.1 - 0.5 sec). My settings works fine with my raspberry pi model b+ with 5G network. Maybe thats the issue.

**Comment by RafaelCota** [comment]
> Try to change the value of timeout to 100 - 500 (0.1 - 0.5 sec). My settings works fine with my raspberry pi model b+ with 5G network. Maybe thats the issue.

It worked with 250... Thank you very much.

**Comment by Jopyth** [comment]
The new version with the changes of shbatm is now merged. 🎉
